name: Terraform Apply

on:
  push:
    branches: [main]

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.TF_ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.TF_ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.TF_ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.TF_ARM_TENANT_ID }}
      ARM_ACCESS_KEY: ${{ secrets.TF_ARM_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: cd terraform/ && terraform init

      - name: Terraform Apply
        run: cd terraform/ && terraform apply -var="client_id=${{ secrets.SPOTIFY_CLIENT_ID }}" -var="client_secret=${{ secrets.SPOTIFY_CLIENT_SECRET }}" -auto-approve
