name: Terraform Apply

on:
  push:
    branches: [ main ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: 7afab6b9-d650-4355-afcf-34831824eddc
      ARM_CLIENT_SECRET: ${{ secrets.TF_ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: a0b32e85-60d6-4ad6-8067-06c26f6b0f6a
      ARM_TENANT_ID: 4124c0dc-2be8-4460-bc50-6b9c2a93b882

    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: cd terraform/ && terraform init

      - name: Terraform Apply
        run: cd terraform/ && terraform apply -var="docker_image_tag=${{ steps.meta.outputs.tags }}" -auto-approve
