name: Terraform Plan and Publish Docker Image

on:
  pull_request:
    branches: [ main ]

jobs:
  terraform:
    name: Terraform Plan
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: 7afab6b9-d650-4355-afcf-34831824eddc
      ARM_CLIENT_SECRET: ${{ secrets.TF_ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: a0b32e85-60d6-4ad6-8067-06c26f6b0f6a
      ARM_TENANT_ID: 4124c0dc-2be8-4460-bc50-6b9c2a93b882

    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: cd terraform/ && terraform init

      - name: Terraform Plan
        run: cd terraform/ && terraform plan -var="client_id=${{ secrets.SPOTIFY_CLIENT_ID }}" -var="client_secret=${{ secrets.SPOTIFY_CLIENT_SECRET }}"
  
  docker:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: nxxqxxj/rnd-sxng
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: nxxqxxj/rnd-sxng:latest
          labels: ${{ steps.meta.outputs.labels }}
